app/posts/urls.py
from django.conf.urls import url
from app.posts import views

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='post-list'),
    url(r'^posts/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='post-detail'),
    url(r'^create/$', views.PostCreate.as_view(), name='post-create')
]

app/utils/urls.py
from django.conf.urls import url
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from app.utils.views import Votes, Comments
from app.utils.models import LikeDislike
from app.posts.models import Post

urlpatterns = [
    # likes / dislikes
    url(r'^like/post/(?P<pk>\d+)/$',
        login_required(Votes.as_view(model=Post, vote_type=LikeDislike.LIKE)),
        name='post-like'),

    url(r'^like/dislike/(?P<pk>\d+)/$',
        login_required(Votes.as_view(model=Post, vote_type=LikeDislike.DISLIKE)),
        name='post-dislike'),


    # comments
    url(r'^comment/post/(?P<pk>\d+)/$',
        login_required(Comments.as_view(model=Post)),
        name='post-comment'),
]

conf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^utils/', include('app.utils.urls', namespace='utils')),

    url(r'^', include('app.posts.urls', namespace='posts')),
    url(r'^', include('app.accounts.urls', namespace='accounts'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/posts/models.py
import os
import uuid

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.conf import settings

from app.utils.models import LikeDislike, Comment
from app.helpers.models import BaseModel


def picture_upload(instance, filename):
    """ upload picture """
    fn, fext = os.path.splitext(filename)
    fn = 'post-image'
    return '/'.join(['posts', f'{fn}-{str(uuid.uuid4())}{fext}'])


class Post(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET('Deleted User'))
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to=picture_upload)

    votes = GenericRelation(LikeDislike)

    comments = GenericRelation(Comment)

    def __str__(self):
        return str(self.pk)


    class Meta:
        ordering = ['-created_at']

app/posts/forms.py
from django import forms

from .models import Post


class CreatePostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'image')

app/posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .models import Post


class PostCreate(CreateView):
    model = Post
    template_name = 'posts/create.html'
    fields = ['image', 'title', 'text']

    def get_success_url(self):
        return '/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return redirect(self.get_success_url())


class PostDetail(DetailView):
    model = Post
    template_name = 'posts/detail.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        comments = self.object.comments.order_by('-created_at')
        paginator = Paginator(comments, 2)
        page = self.request.GET.get('page')

        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            comments = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            comments = paginator.page(paginator.num_pages)
        context['comments'] = comments
        return context


class PostList(ListView):
    model = Post
    template_name = 'posts/list.html'
    paginate_by = 5

    def get_queryset(self):
        query = {k: v for k, v in self.request.GET.items() if k != 'page'}
        if not query:
            return Post.objects.order_by('-created_at')
        else:
            queryset = Post.objects.filter(
                Q(user__email__icontains=query.get('kw')) |
                Q(title__icontains=query.get('kw')) |
                Q(text__icontains=query.get('kw')),
                user__country__icontains=query.get('country'),
                user__city__icontains=query.get('city')
            )
            return queryset

templates/posts/create.html
{% extends 'base.html' %}
{% block title %}Post Create{% endblock %}
{% block content %}
  <div class="container">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Create</button>
    </form>
  </div>
{% endblock %}

templates/posts/detail.html
{% extends 'base.html' %}
{% block title %}Post Detail{% endblock %}
{% block content %}
  <div class="container">
    <div>
      <p>{{ object.title }}</p>
      <img  class="img-fluid" src="{{ object.image.url }}" alt="">
      <p>{{ object.text }}</p>
    </div>
    <div>
      <p>comments:</p>
      <hr>
      <form id="send-comment" data-id="{{ object.pk }}" name="add-coment"  action="{% url 'utils:post-comment' pk=object.pk %}">
        {% csrf_token %}
        <div class="form-group">
          <textarea class="form-control" name="text" id="comment_text" cols="30" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Send</button>
      </form>
      <ul id="comments">
        {% for c in comments %}
        <li>
          <p><small>{{ c.user }}</small></p>
          <p>{{ c.text }}</p>
        </li>
        <hr>
        {% endfor %}
      </ul>
      <div class="pagination">
        <span class="step-links">
          {% if comments.has_previous %}
            <a href="?page={{ comments.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
            Page {{ comments.number }} of {{ comments.paginator.num_pages }}.
          </span>

          {% if comments.has_next %}
            <a href="?page={{ comments.next_page_number }}">next</a>
          {% endif %}
        </span>
      </div>
    </div>
  </div>
{% endblock %}

templates/posts/list.html
{% extends 'base.html' %}
{% block title %}Posts{% endblock %}
{% block content %}
  <div class="container">
  <div class="row">
    <ul class="col-md-8">
      {% for obj in object_list %}
        <li>
          <p>{{ obj.title }}</p>
          <small>by: {{ obj.user.email }} from: {{ obj.user.country }} {{ obj.user.city }}</small>
          <img  class="img-fluid" src="{{ obj.image.url }}" alt="">
          <p>{{ obj.text }}</p>
        </li>
          <div>
            <i class="fa fa-comment" aria-hidden="true"></i> {{ obj.comments.all.count }}
            <span send-to="{% url 'utils:post-like' pk=obj.pk %}" data-id="{{ object.id }}" data-action="like" style="padding:5px;cursor:pointer;">
              <i class="fa fa-thumbs-up" aria-hidden="true"></i>
              <span data-count="like">{{ obj.votes.likes.count }}</span>
            </span>
          </div>
        <a class="btn btn-success" href="{% url 'posts:post-detail' pk=obj.pk %}">Detail</a>
        <hr>
      {% endfor %}
    </ul>
    <div class="col-md-4">
      <a href="{% url 'posts:post-create' %}" class="btn btn-success">Create post</a>
      <form action="" name='myform' method="get">
        <p style="padding-top:15px;"><a href="{% url 'posts:post-list' %}" style="display:block;">All</a></p>
        <input name="kw" type="text" title="" placeholder="by key word">
        <input name="country" type="text" title="" placeholder="by user country">
        <input name="city" type="text" title="" placeholder="by user city">


        <button type="submit" class="btn btn-primary">Search</button>
      </form>
    </div>
    {% if is_paginated %}
    <ul class="pagination col-md-12">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}{{ getvars }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}{{ getvars }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}{{ getvars }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}
  </div>


  </div>
{% endblock %}